---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    helm.sh/chart: {{ $.Chart.Version  }}
spec:
  revisionHistoryLimit: 0
  {{- if not .Values.autoscaling  }}
  replicas: {{ .Values.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if  .Values.pvc }}
  strategy:
    type: Recreate
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        prometheus-managed: "true"
    spec:
      {{- if  .Values.pvc }}
      initContainers:
      - name: chmod
        command: ["/bin/sh","-c"]
        args: ["chmod -R 777 {{ .Values.pvc.path }}"]
        #image: public.ecr.aws/h6j9y1h0/ubuntu:latest
        image: ubuntu:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: {{ .Release.Name }}
          mountPath: {{ .Values.pvc.path }}
      {{- end }}
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}/{{ .Release.Name }}:{{ .Values.image.tag }}"
        {{- with .Values.envFrom }}
        envFrom:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if  .Values.secrets }}
        env:
          {{- range .Values.secrets }}
          {{- range .paths }}
          - name: {{ .objectAlias | upper }}
            valueFrom:
              secretKeyRef:
                name: {{ default $.Release.Name ($.Values.secretNameOverride | default nil) }}
                key: {{ .objectAlias | upper }}
          {{- end }}
          {{- end }}
        {{- end }}
        {{- with .Values.volumeMounts }}
        volumeMounts:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu | default 1 }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu | default 1 }}
            memory: {{ .Values.resources.requests.memory }}
        ports:
        - name: {{ .Release.Name }}
          {{- if  .Values.virtualservice }}
          containerPort: {{ .Values.virtualservice.port | default 3000 }}
          {{- else }}
          containerPort: 3000
          {{- end }}
          protocol: TCP
        {{- if .Values.probes }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.path }}
            port: {{ .Values.virtualservice.port | default 3000 }}
          initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
          successThreshold: {{ .Values.probes.successThreshold }}
          failureThreshold: {{ .Values.probes.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.path }}
            port: {{ .Values.virtualservice.port | default 3000 }}
          initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
          successThreshold: {{ .Values.probes.successThreshold }}
          failureThreshold: {{ .Values.probes.failureThreshold }}
        {{- end }}
      {{- if .Values.serviceAccount }}
      serviceAccount: {{ .Release.Name }}
      serviceAccountName: {{ .Release.Name }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 6 }}
      {{- end }}