{{- if .Values.secrets }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    helm.sh/chart: {{ $.Chart.Version  }}
spec:
  provider: aws
  parameters:
    objects: |
      {{- range .Values.secrets }}
      - objectName: "{{ .objectName }}"
        objectType: "secretsmanager"
        jmesPath:
          {{- range .paths }}
          - path: {{ .path }}
            objectAlias: {{ .objectAlias }}
          {{- end }}
      {{- end }}
  secretObjects:
    {{- range .Values.secrets }}
    - secretName: {{ $.Release.Name }}
      type: Opaque
      data:
        {{- range .paths }}
        - key: {{ .objectAlias | upper }}
          objectName: {{ .objectAlias }}
        {{- end }}
    {{- end }}
{{- end }}