{{- if .Values.virtualservice }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{  .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    helm.sh/chart: {{ $.Chart.Version  }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.virtualservice.port | default 3000 }}
    protocol: "TCP"
    targetPort: {{ .Values.virtualservice.port | default 3000 }}
  selector:
    app: {{ .Release.Name }}
{{ end }}
